### ISSUE TITLE
Remove "Now taking applications" modal when Adding New Project

### ISSUE THREAD

**Issue by shaunop** [voteagora/op-atlas#381] opened 2024-12-09 22:54 UTC
This modal needs to be removed. It appears when a user clicks to "add a project"

<img width="742" alt="Screenshot 2024-12-09 at 2 52 59 PM" src="https://github.com/user-attachments/assets/9304a589-4de6-4097-8a90-1e6fb5d47385">

**Comment by JSeiferth** [comment] 2024-12-10 11:22
Duplicate of https://github.com/voteagora/op-atlas/issues/345

**Closed** 2024-12-10 19:22 UTC
Labels: bug
